//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dasm.rc
//
#define HELPDIALOG_1                    1
#define help_shortcuts                  2
#define Get_Name                        3
#define Search_Dialog                   4
#define S_Box                           5
#define Advanced_Options                6
#define load_box                        7
#define save_box                        8
#define IDC_SEGLISTBOX                  10
#define IDC_GROUPBOX3                   11
#define IDC_OKBUTTON                    12
#define IDC_JUMPTOBUTTON                13
#define IDC_NAMESLISTBOX                14
#define IDC_XREFSLISTBOX                15
#define IDC_IMPORTSLISTBOX              16
#define IDC_EXPORTSLISTBOX              17
#define IDC_LOADDATA                    100
#define IDS_FILTERSAVE                  101
#define IDC_RADIOBUTTON1                101
#define idc_xadd                        101
#define Jaddr_Editor                    101
#define D_help_about                    102
#define save_database                   102
#define D_checktype                     103
#define IDC_GROUPBOX1                   104
#define OEP_Editor                      104
#define IDC_GROUPBOX2                   105
#define main_menu                       106
#define make_string                     107
#define pascal_string                   108
#define line_jumpto                     109
#define make_dword                      110
#define make_word                       111
#define undefine_lines                  112
#define undefine_line                   113
#define make_code                       114
#define view_segment                    115
#define file_open                       117
#define file_save                       118
#define file_exit                       119
#define help_about                      120
#define IDS_FILTERSTRING                121
#define IDC_DEFAULTBUTTON               122
#define IDC_DOSBUTTON                   123
#define IDC_BINBUTTON                   124
#define IDC_LOADRESOURCES               125
#define IDC_32DASM                      126
#define IDC_SEGEDIT                     127
#define IDC_OFFSEDIT                    128
#define IDC_LISTBOX1                    129
#define IDC_PUSHBUTTON1                 130
#define IDC_16DASM                      131
#define load_debug                      132
#define IDC_HELPBUTTON1                 133
#define IDC_BUTTON1                     134
#define Borg_Shutdown                   135
#define Seg_Viewer                      136
#define SEG_TEXTSTART                   137
#define SEG_TEXTEND                     138
#define SEG_TEXTSIZE                    139
#define SEG_TEXTTYPE                    140
#define help_short                      141
#define Names_Viewer                    142
#define NAMES_TEXTSTART                 143
#define NAMES_TEXTEND                   144
#define view_names                      145
#define NAMES_RENAME                    146
#define NAMES_DELETE                    147
#define IDC_NAMEEDIT                    148
#define Name_Location                   149
#define right_click_menu                150
#define Jump_Back                       151
#define dos_string                      152
#define uc_string                       153
#define up_string                       154
#define general_string                  155
#define save_asm                        156
#define view_xrefs                      157
#define Xrefs_Viewer                    158
#define XREFS_DELETE                    159
#define Imports_Viewer                  160
#define IMPORTS_TEXTSTART               161
#define IMPORTS_TEXTEND                 162
#define view_imports                    163
#define demangle_names                  164
#define Exports_Viewer                  165
#define EXPORTS_TEXTSTART               166
#define EXPORTS_TEXTEND                 167
#define view_exports                    168
#define IDC_SEGNAMETEXT                 169
#define argover_dec                     170
#define argover_hex                     171
#define argover_char                    172
#define offset_dseg                     173
#define main_search                     174
#define search_edit                     175
#define search_string                   176
#define search_hex                      177
#define search_decimal                  178
#define search_bytes                    179
#define search_fromcurr                 180
#define search_fromstart                181
#define IDC_GROUPBOX4                   182
#define more_options                    183
#define advanced_pushbp                 184
#define advanced_enter                  185
#define advanced_movbx                  186
#define advanced_aggressive             187
#define advanced_eaxfromesp             188
#define advanced_moveax                 190
#define load_database                   191
#define Comment_Editor                  192
#define idc_website                     193
#define idc_email                       194
#define IDC_COMMENTEDIT                 195
#define Text_Top                        196
#define Text_Bottom                     197
#define Text_Status                     198
#define Block_Dialog                    199
#define Decrypt_Dialog                  200
#define idc_mul                         201
#define idc_rot                         202
#define idc_arrayoffset                 203
#define idc_value                       204
#define idc_arrayseg                    205
#define idc_applytoexe                  206
#define IDC_GROUPBOX5                   207
#define IDC_GROUPBOX6                   208
#define idc_sub                         209
#define float_single                    210
#define idc_add                         210
#define float_double                    211
#define idc_xor                         211
#define float_longdouble                212
#define idc_array                       212
#define line_jumptoarg2                 213
#define idc_dword                       213
#define idc_word                        214
#define get_comment                     215
#define idc_byte                        215
#define set_bg_color                    217
#define set_text_color                  220
#define set_high_color                  221
#define font_ansi                       225
#define font_system                     226
#define font_courier                    227
#define font_courier12                  230
#define font_courier15                  231
#define font_courier10                  232
#define undefine_lines_long             238
#define argnegate                       240
#define block_top                       247
#define block_bottom                    248
#define block_view                      249
#define block_undefine                  250
#define block_saveasm                   251
#define block_savetext                  252
#define IDC_JADDREDIT                   1000
#define IDC_OEPEDIT                     1001
#define IDC_PATCHOEP                    1002
#define CM_ARGUMENTOVERRIDEITEM4        18873
#define change_oep                      40001
#define jump_to                         40002
#define arg_single                      51682
#define search_again                    51683
#define cm_decrypt                      51684
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
